#!/bin/sh

# Network Setup
uci set network.loopback=interface
uci set network.loopback.device='lo'
uci set network.loopback.proto='static'
uci set network.loopback.ipaddr='127.0.0.1'
uci set network.loopback.netmask='255.0.0.0'

uci set network.globals=globals
uci set network.globals.ula_prefix='fd12:3456:789a::/48'

uci set network.@device[-1]=device
uci set network.@device[-1].name='br-lan'
uci set network.@device[-1].type='bridge'
uci set network.@device[-1].ports='eth0'
uci add_list network.@device[-1].ports='lan1'
uci add_list network.@device[-1].ports='lan2'
uci add_list network.@device[-1].ports='lan3'

uci set network.lan=interface
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.1.1'
uci set network.lan.netmask='255.255.255.0'

uci set network.wan=interface
uci set network.wan.device='eth1'
uci set network.wan.proto='dhcp'

uci commit network
uci commit system

exit 0
